FROM ubuntu:22.04 AS builder

RUN apt-get update && \
    apt-get install -y \
    curl \
    zip \
    nginx && \
    rm -rf /var/lib/apt/lists/*

COPY . /var/www/html

FROM nginx:alpine

COPY --from=builder /var/www/html/ /usr/share/nginx/html/

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-c", "/etc/nginx/nginx.conf"]